# Generated by Django 2.0.6 on 2018-07-30 17:27

from django.db import migrations, models
import django.utils.timezone
import storages.backends.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=75, verbose_name='Ім`я')),
                ('mail', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, default=None, storage=storages.backends.ftp.FTPStorage(), upload_to='attachments', verbose_name='Вкладення')),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
    ]
