# Generated by Django 2.0.6 on 2018-10-16 18:55

from django.db import migrations, models
import django.utils.timezone
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterField(
            model_name='review',
            name='attachment',
            field=models.FileField(blank=True, storage=storages.backends.ftp.FTPStorage(), upload_to='attachments', verbose_name='Вкладення'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='review',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='Непрочитане'),
        ),
    ]
