# Generated by Django 2.0.6 on 2018-06-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_auto_20180601_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(default=1, max_length=10, verbose_name='Правильна відповідь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[('1', 'З однією правильною відповіддю'), ('2', 'Встановлення відповідності'), ('3', 'З відкритою відповіддю')], default='1', verbose_name='Тип завдання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37)], default='1', verbose_name='Номер завдання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='probne',
            field=models.BooleanField(verbose_name='Пробне ЗНО'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(upload_to='uploads', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Theme', verbose_name='Розділ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='year',
            field=models.IntegerField(choices=[(2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='Рік'),
        ),
    ]
