# Generated by Django 2.0.6 on 2018-06-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0003_auto_20180603_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Теми'},
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
    ]
