# Generated by Django 2.0.6 on 2018-07-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0005_auto_20180628_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='probne',
            field=models.IntegerField(choices=[(1, 'Основне'), (2, 'Пробне'), (3, 'Додаткова сесія')], default='1', verbose_name='Тип ЗНО'),
        ),
    ]
