# Generated by Django 2.0.6 on 2018-07-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0006_auto_20180718_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='probne',
            new_name='zno_type',
        ),
    ]
