# Generated by Django 2.0.6 on 2018-07-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0007_auto_20180718_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='name',
            new_name='theme',
        ),
    ]
