# Generated by Django 2.0.6 on 2018-07-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0008_auto_20180718_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='theme',
            new_name='name',
        ),
    ]
