# Generated by Django 2.0.6 on 2018-10-16 18:55

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0009_auto_20180718_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(max_length=12, verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38)], default='1', verbose_name='Номер завдання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image',
            field=models.ImageField(storage=storages.backends.ftp.FTPStorage(), upload_to='uploads', verbose_name='Завдання'),
        ),
    ]
