# Generated by Django 2.0.6 on 2018-10-28 15:41

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physics', '0010_auto_20181016_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Підбірка')),
                ('cover', models.ImageField(blank=True, storage=storages.backends.ftp.FTPStorage(), upload_to='bundles', verbose_name='Обкладинка')),
                ('author_id', models.IntegerField(default='3', verbose_name='Автор')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('edited_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Останні зміни')),
                ('shared', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Доступно для')),
                ('tasks', models.ManyToManyField(blank=True, to='physics.Task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Підбірка',
                'verbose_name_plural': 'Підбірки',
            },
        ),
    ]
