# Generated by Django 2.0.6 on 2018-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0013_auto_20181223_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='theme',
            field=models.CharField(default='', max_length=200),
        ),
    ]
