# Generated by Django 2.0.6 on 2018-12-31 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0014_testanswer_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name_plural': 'Відповіді користувачів'},
        ),
        migrations.AlterField(
            model_name='bundle',
            name='cover',
            field=models.ImageField(default='bundles/bundle.jpg', storage=storages.backends.ftp.FTPStorage(), upload_to='bundles', verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата відповіді'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='is_true',
            field=models.BooleanField(verbose_name='Правильна відповідь'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Task', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Theme', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=12, verbose_name='Відповідь користувача'),
        ),
    ]
