# Generated by Django 2.0.6 on 2018-12-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0015_auto_20181231_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Theme', verbose_name='Тема'),
        ),
    ]
